# Site
name: "notesmachine"
title: "notesmachine"
description: "Learn to decode piano sheet music 🎹"
logo: 'assets/01-NOTES/gear-notes-feb-sml.png'
favicon: 'assets/01-NOTES/gear-notes-feb-sml.png'
baseurl: www.notesmachine.com
# google_analytics: 'UA-46278016-1'
disqus: 'website'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mon:
    name: Mon
    display_name: Mon
    avatar: 'assets/01-NOTES/gear-notes-feb-sml.png'
    email: accounts@notesmachine.com
    web: https://www.notesmachine.com
    twitter: https://twitter.com/notesmachine
    instagram: https://www.instagram.com/notesmachine
    description: "creator of notesmachine 🎵. moonlight pianist 🌙. balancing web realms and melodic dreams with merlot in hand. #notesmachine 🍷✨"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, vendor]
